name: AOC
version: 0.0.1
synopsis: Advent of code solutions for 2021
description: See README at <https://github.com/japiirainen/aoc-2021#readme>
maintainer: Joona Piirainen <joona.piirainen@gmail.com>
github: japiirainen/aoc-2021
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base
  - megaparsec
  - mtl
  - containers
  - pretty
  - text
  - directory
  - selective
  - vector
  - lens

library:
  source-dirs: 
    - lib
  exposed-modules:
    - AOC.List.Transformer
    - AOC.List.Extended
    - AOC.Parsija
    - AOC.V2
    - AOC.V2.Box
    - AOC.Grid
    - AOC.Main
    - AOC.Foldable
    - AOC.Dijkstra
    - AOC.Vector.Extra
    - AOC.Grid.Bounded
    - AOC.Functor.Fix

executables:
  2021-01:
    source-dirs: "2021"
    main: 01.hs
    dependencies: AOC
  2021-02:
    source-dirs: "2021"
    main: 02.hs
    dependencies: AOC
  2021-03:
    source-dirs: "2021"
    main: 03.hs
    dependencies: AOC
  2021-04:
    source-dirs: "2021"
    main: 04.hs
    dependencies: AOC
  2021-05:
    source-dirs: "2021"
    main: 05.hs
    dependencies: AOC
  2021-06:
    source-dirs: "2021"
    main: 06.hs
    dependencies: AOC
  2021-07:
    source-dirs: "2021"
    main: 07.hs
    dependencies: AOC
  2021-08:
    source-dirs: "2021"
    main: 08.hs
    dependencies: AOC
  2021-09:
    source-dirs: "2021"
    main: 09.hs
    dependencies: AOC
  2021-10:
    source-dirs: "2021"
    main: 10.hs
    dependencies: AOC
  2021-11:
    source-dirs: "2021"
    main: 11.hs
    dependencies: AOC
  2021-12:
    source-dirs: "2021"
    main: 12.hs
    dependencies: AOC
  2021-13:
    source-dirs: "2021"
    main: 13.hs
    dependencies: AOC
  2021-14:
    source-dirs: "2021"
    main: 14.hs
    dependencies: AOC
  2021-15:
    source-dirs: "2021"
    main: 15.hs
    dependencies: AOC
  2021-16:
    source-dirs: "2021"
    main: 16.hs
    dependencies: AOC
